apiVersion: v1
kind: Service
metadata:
  name: foodadvisor-api
spec:
  type: NodePort
  selector:
    app: foodadvisor-api
  ports:
    - protocol: TCP
      port: 1337
      nodePort: 31337 # nodeport range: 30000-32767
