apiVersion: v1
kind: Service
metadata:
  name: foodadvisor-api-service
spec:
  type: ClusterIP
  selector:
    app: foodadvisor-api
    component: api
  ports:
    - protocol: TCP
      port: 1337
      targetPort: 1337
