apiVersion: apps/v1
kind: Deployment
metadata:
  name: foodadvisor-client
spec:
  selector:
    matchLabels:
      app: foodadvisor-client
      component: client
  template:
    metadata:
      labels:
        app: foodadvisor-client
        component: client
    spec:
      containers:
        - name: foodadvisor-client
          image: luthda/foodadvisor-client:001
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: foodadvisor-client-conf
            - secretRef:
                name: foodadvisor-client-secret
