apiVersion: v1
kind: Service
metadata:
  name: foodadvisor-client-service
spec:
  type: ClusterIP
  selector:
    app: foodadvisor-client
    component: client
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
