apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-persistent-volume-claim
  labels:
    app: postgres-db
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
