apiVersion: v1
kind: Service
metadata:
  name: strapi-app
spec:
  type: NodePort
  selector:
    app: strapi-app
  ports:
    - protocol: TCP
      port: 1337
      nodePort: 31337 # nodeport range: 30000-32767
